model_name: meta-llama/Llama-3.2-3B-Instruct
output_dir: artifacts/model_v3a
logging_dir: artifacts/logs
lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules: [q_proj, v_proj]

training:
  learning_rate: 1e-5
  batch_size: 6
  gradient_accumulation_steps: 2
  num_train_epochs: 2
  seed: 42
  bf16: true
  gradient_checkpointing: true
  qlora: true

data:
  #train_file: data/processed/train.jsonl
  train_file: data/processed/train_v1.jsonl
  val_file: data/processed/valid.jsonl
 